# Generated by Django 4.2.9 on 2024-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist_users',
            name='status',
        ),
    ]
