# Generated by Django 4.2.9 on 2024-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message_sender_message_thread_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
