# Generated by Django 4.2.9 on 2024-06-10 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofilemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
