# Generated by Django 4.2.9 on 2024-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_games_player1_alter_games_player2_usergames'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id42',
            field=models.IntegerField(default=100),
        ),
    ]
