# Generated by Django 4.2.9 on 2024-07-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_tournament_players_tournament_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='currentGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.games'),
        ),
    ]
