# Generated by Django 4.2.9 on 2024-07-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tournament_currentgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='currentGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.games'),
        ),
    ]
