# Generated by Django 4.2.9 on 2024-07-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_tournamentmatch_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toutnament_matches', to='users.tournament'),
        ),
    ]
