# Generated by Django 4.2.9 on 2024-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_users_id42'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
