# Generated by Django 4.2.9 on 2024-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tournament_tournament_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
