# Generated by Django 4.2.9 on 2024-07-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_games_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='currentGame',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_tree',
        ),
        migrations.AddField(
            model_name='games',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tournament'),
        ),
    ]
