# Generated by Django 4.2.9 on 2024-07-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_tournament_currentgame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='round',
        ),
    ]
