# Generated by Django 4.2.9 on 2024-07-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_games_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.settings'),
        ),
    ]
